-- Copyright (c) 2025 albaDsl

module TestLibauthVectorsExclusions2026 where

import Data.Text qualified as T

excludeStandard :: [T.Text]
excludeStandard =
  [ "087945", -- passed validation but failed metrics!
    "tt3jp0", -- passed validation but failed metrics!
    "tj25sm", -- passed validation but failed metrics!
    "r4q25v", -- passed validation but failed metrics!
    "0v668j", -- passed validation but failed metrics!
    "jc2fcm", -- passed validation but failed metrics!
    "99kqf0", -- passed validation but failed metrics!
    "lg7nx4", -- passed validation but failed metrics!
    "9s36n8", -- passed validation but failed metrics!
    "m79792", -- passed validation but failed metrics!
    "sm3xfx", -- passed validation but failed metrics!
    "lpxnl3", -- passed validation but failed metrics!
    "s53gs0", -- passed validation but failed metrics!
    "zk2xyq", -- passed validation but failed metrics!
    "f347gs", -- passed validation but failed metrics!
    "zahy75", -- passed validation but failed metrics!
    "2t7wu4", -- passed validation but failed metrics!
    "f25vp8", -- passed validation but failed metrics!
    "uxusx5", -- passed validation but failed metrics!
    "sh9svr", -- passed validation but failed metrics!
    "77swq4", -- passed validation but failed metrics!
    "9s9rap", -- passed validation but failed metrics!
    "m7df5q", -- passed validation but failed metrics!
    "hscjax", -- passed validation but failed metrics!
    "ahz9kk", -- passed validation but failed metrics!
    "9ysg97", -- passed validation but failed metrics!
    "6tgrkl", -- passed validation but failed metrics!
    "uflamw", -- passed validation but failed metrics!
    "pmz3u5", -- passed validation but failed metrics!
    "t5spqa", -- passed validation but failed metrics!
    "8avd2k", -- passed validation but failed metrics!
    "pr3n98", -- passed validation but failed metrics!
    "9jm3d4", -- passed validation but failed metrics!
    "lgr4rs", -- passed validation but failed metrics!
    "wcy5jc", -- passed validation but failed metrics!
    "kfzpdf", -- passed validation but failed metrics!
    "jucs7r", -- passed validation but failed metrics!
    "uks569", -- passed validation but failed metrics!
    "fjxma7", -- passed validation but failed metrics!
    "pecq63", -- passed validation but failed metrics!
    "3uatj6", -- passed validation but failed metrics!
    "m4pa8g", -- passed validation but failed metrics!
    "67am0u", -- passed validation but failed metrics!
    "vcg6ng", -- passed validation but failed metrics!
    "jtvpgp", -- passed validation but failed metrics!
    "2r8um4", -- passed validation but failed metrics!
    "fa3jcl", -- passed validation but failed metrics!
    "prphj3", -- passed validation but failed metrics!
    "6dd50f", -- passed validation but failed metrics!
    "68uysj", -- passed validation but failed metrics!
    "jkc70n", -- passed validation but failed metrics!
    "zszcpl", -- passed validation but failed metrics!
    "0a86ft", -- passed validation but failed metrics!
    "gycrz2", -- passed validation but failed metrics!
    "maamwz", -- passed validation but failed metrics!
    "2tpq0u", -- passed validation but failed metrics!
    "mdzw2l", -- passed validation but failed metrics!
    "jckqzk", -- passed validation but failed metrics!
    "gnqwhe", -- passed validation but failed metrics!
    "3q7mzd", -- passed validation but failed metrics!
    "w50l55", -- passed validation but failed metrics!
    "svfqs5", -- passed validation but failed metrics!
    "s9yl8p", -- passed validation but failed metrics!
    "u2pfgg", -- passed validation but failed metrics!
    "fmy0mj", -- passed validation but failed metrics!
    "693g3y", -- passed validation but failed metrics!
    "v2crp8", -- passed validation but failed metrics!
    "a4hpkq", -- passed validation but failed metrics!
    "jn0yyk", -- passed validation but failed metrics!
    "jfzen0", -- passed validation but failed metrics!
    "lqlurz", -- passed validation but failed metrics!
    "sdy4mu", -- passed validation but failed metrics!
    "qs75fx", -- passed validation but failed metrics!
    "qacy4z", -- passed validation but failed metrics!
    "y5kgz5", -- passed validation but failed metrics!
    "4tda00", -- passed validation but failed metrics!
    "uh7szc", -- passed validation but failed metrics!
    "6tfx66", -- passed validation but failed metrics!
    "rxdqw8", -- passed validation but failed metrics!
    "klq3ut", -- passed validation but failed metrics!
    "yq0f3z", -- passed validation but failed metrics!
    "szz6xc", -- passed validation but failed metrics!
    "5pnls6", -- passed validation but failed metrics!
    "2hadru", -- passed validation but failed metrics!
    "fzgycf", -- passed validation but failed metrics!
    "mpxcdv", -- passed validation but failed metrics!
    "fcddc2", -- passed validation but failed metrics!
    "vc8su9", -- passed validation but failed metrics!
    "armygs", -- passed validation but failed metrics!
    "tutkzs", -- passed validation but failed metrics!
    "ph2ygv", -- passed validation but failed metrics!
    "844fz8", -- passed validation but failed metrics!
    "lg7pj0", -- passed validation but failed metrics!
    "edqhgv", -- passed validation but failed metrics!
    "4x57ap", -- passed validation but failed metrics!
    "l4e855", -- passed validation but failed metrics!
    "2s2acm", -- passed validation but failed metrics!
    "h8xjn9", -- passed validation but failed metrics!
    "yphyav", -- passed validation but failed metrics!
    "allyh5", -- passed validation but failed metrics!
    "yc8sh0", -- passed validation but failed metrics!
    "3q0yln", -- passed validation but failed metrics!
    "zlga55", -- passed validation but failed metrics!
    "cxzkrm", -- passed validation but failed metrics!
    "mnq063", -- passed validation but failed metrics!
    "ax28uc", -- passed validation but failed metrics!
    "zdrlhg", -- passed validation but failed metrics!
    "cp6p9l", -- passed validation but failed metrics!
    "tsnnw5", -- passed validation but failed metrics!
    "236pcv", -- passed validation but failed metrics!
    "vzw5hn", -- passed validation but failed metrics!
    "tu2fpy", -- passed validation but failed metrics!
    "z2mq80", -- passed validation but failed metrics!
    "etryws", -- passed validation but failed metrics!
    "l4cknc", -- passed validation but failed metrics!
    "nskc4c", -- passed validation but failed metrics!
    "8y3yaw", -- passed validation but failed metrics!
    "g2907w", -- passed validation but failed metrics!
    "x5yzan", -- passed validation but failed metrics!
    "s0l2qa", -- passed validation but failed metrics!
    "70490l", -- passed validation but failed metrics!
    "5tvspc", -- passed validation but failed metrics!
    "sv35a4", -- passed validation but failed metrics!
    "t49vf2", -- passed validation but failed metrics!
    "34gps4", -- passed validation but failed metrics!
    "9cm4fg", -- passed validation but failed metrics!
    "q295ee", -- passed validation but failed metrics!
    "csz6e8", -- passed validation but failed metrics!
    "ncnmn5", -- passed validation but failed metrics!
    "3fyppr", -- passed validation but failed metrics!
    "749u9s", -- passed validation but failed metrics!
    "kn0w27", -- passed validation but failed metrics!
    "ellavg", -- passed validation but failed metrics!
    "suld94", -- passed validation but failed metrics!
    "yx9ahq", -- passed validation but failed metrics!
    "5kl87z", -- passed validation but failed metrics!
    "p9rxct", -- passed validation but failed metrics!
    "xavve7", -- passed validation but failed metrics!
    "5t39us", -- passed validation but failed metrics!
    "ume6ry", -- passed validation but failed metrics!
    "z6rwf6", -- passed validation but failed metrics!
    "jsnfzw", -- passed validation but failed metrics!
    "f64dkl", -- passed validation but failed metrics!
    "apkffe", -- passed validation but failed metrics!
    "tnkx0h", -- passed validation but failed metrics!
    "pj539z", -- passed validation but failed metrics!
    "f50d92", -- passed validation but failed metrics!
    "jnh8wm", -- passed validation but failed metrics!
    "std4tm", -- passed validation but failed metrics!
    "4mt2ay", -- passed validation but failed metrics!
    "37c405", -- passed validation but failed metrics!
    "6tgkzk", -- passed validation but failed metrics!
    "xu038q", -- passed validation but failed metrics!
    "46dnx8", -- passed validation but failed metrics!
    "4wx3w8", -- passed validation but failed metrics!
    "5v7mxw", -- passed validation but failed metrics!
    "hkrg6v", -- passed validation but failed metrics!
    "8cy0au", -- passed validation but failed metrics!
    "7qghpq", -- passed validation but failed metrics!
    "9sjcr2", -- passed validation but failed metrics!
    "85kkpg", -- passed validation but failed metrics!
    "ws5t8h", -- passed validation but failed metrics!
    "3t0dcu", -- passed validation but failed metrics!
    "ngeac3", -- passed validation but failed metrics!
    "8k7ujp", -- passed validation but failed metrics!
    "s494m6", -- passed validation but failed metrics!
    "0c7an9", -- passed validation but failed metrics!
    "e8k6l7", -- passed validation but failed metrics!
    "gsn904", -- passed validation but failed metrics!
    "t7v99x", -- passed validation but failed metrics!
    "cpyag8", -- passed validation but failed metrics!
    "m9tfsx", -- passed validation but failed metrics!
    "69v35d", -- passed validation but failed metrics!
    "4hvm5s", -- passed validation but failed metrics!
    "95e2cu", -- passed validation but failed metrics!
    "dzju7s", -- passed validation but failed metrics!
    "h3cd9e", -- passed validation but failed metrics!
    "js98nz", -- passed validation but failed metrics!
    "mtls6p", -- passed validation but failed metrics!
    "d7jjlf", -- passed validation but failed metrics!
    "ylr2ex", -- passed validation but failed metrics!
    "gsphf3", -- passed validation but failed metrics!
    "gdeje8", -- passed validation but failed metrics!
    "hn74zw", -- passed validation but failed metrics!
    "eyjh45", -- passed validation but failed metrics!
    "tvljz5", -- passed validation but failed metrics!
    "8na0ju", -- passed validation but failed metrics!
    "puz0qm", -- passed validation but failed metrics!
    "g2qy4w", -- passed validation but failed metrics!
    "gxv7an", -- passed validation but failed metrics!
    "2zjlkx", -- passed validation but failed metrics!
    "9snxxx", -- passed validation but failed metrics!
    "venvnq", -- passed validation but failed metrics!
    "sznut8", -- passed validation but failed metrics!
    "0gq99u", -- passed validation but failed metrics!
    "uxuftk", -- passed validation but failed metrics!
    "0cc858", -- passed validation but failed metrics!
    "xjjmlx", -- passed validation but failed metrics!
    "xdusl9", -- passed validation but failed metrics!
    "2gsr9l", -- passed validation but failed metrics!
    "fm34pk" -- passed validation but failed metrics!
  ]

excludeNonStandardInNonStandardMode :: [T.Text]
excludeNonStandardInNonStandardMode = []

excludeNonStandardInStandardMode :: [T.Text]
excludeNonStandardInStandardMode = []

excludeInvalid :: [T.Text]
excludeInvalid = []
