cabal-version:  3.6
name:           alba
version:        0.1.0.0
category:       application
author:         albadsl@proton.me

extra-source-files:
    src/Alba/Vm/Common/Html/style.css
    src/Alba/Vm/Common/Html/script.js

common shared-properties
  default-language: GHC2021
  default-extensions:
      AllowAmbiguousTypes
      DataKinds
      DeriveAnyClass
      DuplicateRecordFields
      GADTs
      LambdaCase
      NoFieldSelectors
      OverloadedLabels
      OverloadedRecordDot
      OverloadedStrings
      OverloadedLists
      PatternSynonyms
      PartialTypeSignatures
      QuasiQuotes
      RecordWildCards
      TypeFamilies
      UndecidableInstances
  other-extensions: Strict TemplateHaskell MagicHash QuasiQuotes
  ghc-options: -fno-ignore-asserts -Wall -Werror
               -- Disable some warnings during development.
               -- -Wno-partial-type-signatures
               -- -Wno-unused-imports
               -- -Wno-unused-top-binds
               -- -Wno-unused-local-binds
               -- -Wno-unused-matches

  build-depends:
      aeson,
      aeson-pretty,
      array,
      base,
      base16,
      binary,
      blaze-html,
      blaze-markup,
      bytestring,
      containers,
      crypton,
      dhall,
      directory,
      entropy,
      file-embed,
      filepath,
      foldl,
      generic-lens,
      haskoin-core-bch-lite,
      here,
      -- liquidhaskell == 0.9.8.2, -- Disable for now.
      http-conduit,
      bchn-secp256k1,
      memory,
      microlens,
      mtl,
      optparse-applicative,
      pretty-simple,
      secp256k1-haskell,
      tasty,
      tasty-hunit,
      tasty-quickcheck,
      template-haskell,
      text,
      time,
      turtle,
      QuickCheck,
      vector

library
  import: shared-properties
  exposed-modules:
      Alba.Dsl.V1.Bch2025,
      Alba.Dsl.V1.Bch2025.Contract.Math,
      Alba.Dsl.V1.Bch2025.Contract.Prelude,
      Alba.Dsl.V1.Bch2025.Infix,
      Alba.Dsl.V1.Bch2025.Lang,
      Alba.Dsl.V1.Bch2025.LangArgs,
      Alba.Dsl.V1.Bch2025.LangUntyped,
      Alba.Dsl.V1.Bch2025.Ops,
      Alba.Dsl.V1.Bch2025.OpsUntyped,
      Alba.Dsl.V1.Bch2025.Stack,
      Alba.Dsl.V1.Bch2025.TxDsl,
      Alba.Dsl.V1.Bch2025.Version,
      Alba.Dsl.V1.Bch2026,
      Alba.Dsl.V1.Bch2026.Contract.Applicative,
      Alba.Dsl.V1.Bch2026.Contract.Bytes128,
      Alba.Dsl.V1.Bch2026.Contract.Int64,
      Alba.Dsl.V1.Bch2026.Contract.Int8,
      Alba.Dsl.V1.Bch2026.Contract.Lzss,
      Alba.Dsl.V1.Bch2026.Contract.Math,
      Alba.Dsl.V1.Bch2026.Contract.Maybe,
      Alba.Dsl.V1.Bch2026.Contract.PackFs,
      Alba.Dsl.V1.Bch2026.Contract.Prelude,
      Alba.Dsl.V1.Bch2026.Contract.Shorthand,
      Alba.Dsl.V1.Bch2026.Contract.Tuple,
      Alba.Dsl.V1.Bch2026.Contract.TupleFs,
      Alba.Dsl.V1.Bch2026.Contract.Vector,
      Alba.Dsl.V1.Bch2026.Contract.ExternalLib,
      Alba.Dsl.V1.Bch2026.Contract.ExternalLibs.Dc,
      Alba.Dsl.V1.Bch2026.Contract.ExternalLibs.Vc,
      Alba.Dsl.V1.Bch2026.ExternalLib,
      Alba.Dsl.V1.Bch2026.Lang,
      Alba.Dsl.V1.Bch2026.LangArgs,
      Alba.Dsl.V1.Bch2026.Ops,
      Alba.Dsl.V1.Bch2026.OpsUntyped,
      Alba.Dsl.V1.Bch2026.TxDsl,
      Alba.Dsl.V1.Bch2026.Stack,
      Alba.Dsl.V1.Common,
      Alba.Dsl.V1.Common.CashScriptOptimizerRules,
      Alba.Dsl.V1.Common.Compile,
      Alba.Dsl.V1.Common.CompilerUtils,
      Alba.Dsl.V1.Common.Contract,
      Alba.Dsl.V1.Common.ContractCashScriptArtifact,
      Alba.Dsl.V1.Common.ContractDoc,
      Alba.Dsl.V1.Common.FlippedCons,
      Alba.Dsl.V1.Common.FunctionState,
      Alba.Dsl.V1.Common.FunctionStateResolved,
      Alba.Dsl.V1.Common.FunctionTableJson,
      Alba.Dsl.V1.Common.FunctionTableText,
      Alba.Dsl.V1.Common.Lang,
      Alba.Dsl.V1.Common.LangArgs,
      Alba.Dsl.V1.Common.LangDispatch,
      Alba.Dsl.V1.Common.Listing,
      Alba.Dsl.V1.Common.Lzss,
      Alba.Dsl.V1.Common.OpcodeL3,
      Alba.Dsl.V1.Common.RuntimeLib,
      Alba.Dsl.V1.Common.Stack,
      Alba.Dsl.V1.Common.StackUntyped,
      Alba.Dsl.V1.Common.TermClass,
      Alba.Dsl.V1.Common.ThUtils,
      Alba.Dsl.V1.Common.TypeFamilies,
      Alba.Dsl.V1.Common.Version,
      Alba.Misc.Bchn,
      Alba.Misc.Cmd,
      Alba.Misc.Debug,
      Alba.Misc.Haskoin,
      Alba.Misc.KeyPair,
      Alba.Misc.Logging,
      Alba.Misc.MockVals,
      Alba.Misc.Opts,
      Alba.Misc.Utils,
      Alba.Misc.Wallet,
      Alba.Node.Policy,
      Alba.Node.TxVerify,
      Alba.Node.ValidateTokens,
      Alba.Node.Validation,
      Alba.Node.ValidationFailure,
      Alba.Tx.Bch2025,
      Alba.Tx.Bch2025.Constants,
      Alba.Tx.Bch2025.Hash,
      Alba.Tx.Bch2025.SerializationUtils,
      Alba.Tx.Bch2025.Tx,
      Alba.Tx.Bch2025.TxId,
      Alba.Tx.Bch2025.TxIn,
      Alba.Tx.Bch2025.TxOut,
      Alba.Tx.Bch2025.TxOuts,
      Alba.Vm.Bch2025,
      Alba.Vm.Bch2025.OpClasses,
      Alba.Vm.Bch2025.SigCheckUtils,
      Alba.Vm.Bch2025.SigEncoding,
      Alba.Vm.Bch2025.Utils,
      Alba.Vm.Bch2025.Vm,
      Alba.Vm.Bch2025.VmOpArithmetic,
      Alba.Vm.Bch2025.VmOpBitwiseLogic,
      Alba.Vm.Bch2025.VmOpBytes,
      Alba.Vm.Bch2025.VmOpConstants,
      Alba.Vm.Bch2025.VmOpDiscouragedNops,
      Alba.Vm.Bch2025.VmOpEqualityAndConditionals,
      Alba.Vm.Bch2025.VmOpHash,
      Alba.Vm.Bch2025.VmOpIntrospection,
      Alba.Vm.Bch2025.VmOpLocktime,
      Alba.Vm.Bch2025.VmOpMultiSig,
      Alba.Vm.Bch2025.VmOpSig,
      Alba.Vm.Bch2025.VmOpStack,
      Alba.Vm.Bch2025.VmOpTokenIntrospection,
      Alba.Vm.Bch2025.VmOps,
      Alba.Vm.Bch2025.VmParams,
      Alba.Vm.Bch2025.VmSigHash,
      Alba.Vm.Bch2026,
      Alba.Vm.Bch2026.OpClasses,
      Alba.Vm.Bch2026.Vm,
      Alba.Vm.Bch2026.VmOpBitwiseLogic,
      Alba.Vm.Bch2026.VmOpDefineInvoke,
      Alba.Vm.Bch2026.VmOpEval,
      Alba.Vm.Bch2026.VmOpLoops,
      Alba.Vm.Bch2026.VmOps,
      Alba.Vm.Bch2026.VmParams,
      Alba.Vm.Common,
      Alba.Vm.Common.BasicTypes,
      Alba.Vm.Common.Crypto,
      Alba.Vm.Common.Logging,
      Alba.Vm.Common.LoggingHtml,
      Alba.Vm.Common.LoggingHtmlAssets,
      Alba.Vm.Common.LoggingText,
      Alba.Vm.Common.LoggingTree,
      Alba.Vm.Common.OpClasses,
      Alba.Vm.Common.OpcodeL1,
      Alba.Vm.Common.OpcodeL2,
      Alba.Vm.Common.ScriptError,
      Alba.Vm.Common.StackElement,
      Alba.Vm.Common.Tx,
      Alba.Vm.Common.TxContext,
      Alba.Vm.Common.Utils,
      Alba.Vm.Common.Vm,
      Alba.Vm.Common.VmBool,
      Alba.Vm.Common.VmInteger,
      Alba.Vm.Common.VmLimits,
      Alba.Vm.Common.VmParams,
      Alba.Vm.Common.VmStack,
      Alba.Vm.Common.VmState,
      DslDemo.EllipticCurve.Affine,
      DslDemo.EllipticCurve.AffineAdd,
      DslDemo.EllipticCurve.Constants,
      DslDemo.EllipticCurve.Field,
      DslDemo.EllipticCurve.Jacobian,
      DslDemo.EllipticCurve.JacobianAdd,
      DslDemo.EllipticCurve.JacobianPoint,
      DslDemo.EllipticCurve.JacobianWindowed,
      DslDemo.EllipticCurve.Native.Affine,
      DslDemo.EllipticCurve.Native.Constants,
      DslDemo.EllipticCurve.Native.FieldElement,
      DslDemo.EllipticCurve.Native.Jacobian,
      DslDemo.EllipticCurve.Point,
      DslDemo.EllipticCurve.LookupTable,
      DslDemo.Exponentiation,
      DslDemo.MergeSort.MergeSort,
      DslDemo.TurtleVm.Bch2025.MiniTurtleVm101,
      DslDemo.TurtleVm.Bch2025.Tuple,
      DslDemo.TurtleVm.Bch2025.TurtleOpArithmetic,
      DslDemo.TurtleVm.Bch2025.TurtleOpBitwiseLogic,
      DslDemo.TurtleVm.Bch2025.TurtleOpBytes,
      DslDemo.TurtleVm.Bch2025.TurtleOpConditionals,
      DslDemo.TurtleVm.Bch2025.TurtleOpConstants,
      DslDemo.TurtleVm.Bch2025.TurtleOpCryptography,
      DslDemo.TurtleVm.Bch2025.TurtleOpIntrospection,
      DslDemo.TurtleVm.Bch2025.TurtleOpStack,
      DslDemo.TurtleVm.Bch2025.TurtleVm,
      DslDemo.TurtleVm.Bch2025.TurtleVmCondStack,
      DslDemo.TurtleVm.Bch2025.TurtleVmState,
      DslDemo.TurtleVm.Bch2025.TurtleVmStateSimple,
      DslDemo.TurtleVm.Bch2025.TurtleVmUtils,
      DslDemo.TurtleVm.Bch2025.TurtleVmUtilsUntyped,
      DslDemo.TurtleVm.Bch2026.Tuple,
      DslDemo.TurtleVm.Bch2026.TurtleOpAltStack,
      DslDemo.TurtleVm.Bch2026.TurtleOpIf,
      DslDemo.TurtleVm.Bch2026.TurtleVm,
      DslDemo.TurtleVm.Bch2026.TurtleVmCondStack,
      DslDemo.TurtleVm.Bch2026.TurtleVmDispatchTable,
      DslDemo.TurtleVm.Bch2026.TurtleVmState,
      DslDemo.TurtleVm.Bch2026.TurtleVmStateSimple,
      DslDemo.TurtleVm.Bch2026.TurtleVmUtils,
      DslDemo.TurtleVm.Bch2026.TurtleVmUtilsUntyped,
      DslDemo.TurtleVm.Common.Maybe,
  hs-source-dirs: src

executable alba
  import: shared-properties
  main-is: main.hs
  hs-source-dirs: apps/alba test
  ghc-options: -threaded -rtsopts -with-rtsopts=-N
  other-modules: LibauthFileParse, LibauthSupport
  build-depends: alba, scientific

executable simpleP2pkh
  import: shared-properties
  hs-source-dirs: apps/contracts/simpleP2pkh
  main-is: main.hs
  other-modules: Opts
  ghc-options: -threaded -rtsopts -with-rtsopts=-N
  build-depends: alba

executable transferWithTimeout
  import: shared-properties
  hs-source-dirs: apps/contracts/transferWithTimeout
  main-is: main.hs
  other-modules: Contract, ContractApi, Opts, Params, Spend, Test
  ghc-options: -threaded -rtsopts -with-rtsopts=-N
  build-depends: alba

executable lastWill
  import: shared-properties
  hs-source-dirs: apps/contracts/lastWill
  main-is: main.hs
  other-modules: Contract, ContractApi, Opts, Params, Spend, Test
  ghc-options: -threaded -rtsopts -with-rtsopts=-N
  build-depends: alba

executable miniTurtleChallenge
  import: shared-properties
  hs-source-dirs: apps/contracts/miniTurtleChallenge
  main-is: main.hs
  other-modules: Contract, ContractApi, Opts, Params, Spend, Test
  ghc-options: -threaded -rtsopts -with-rtsopts=-N
  build-depends: alba

executable permutationChallenge
  import: shared-properties
  hs-source-dirs: apps/contracts/permutationChallenge
  main-is: main.hs
  other-modules: Contract, ContractApi, Opts, Params, Deploy, Spend, Test
  ghc-options: -threaded -rtsopts -with-rtsopts=-N
  build-depends: alba

executable demo
  import: shared-properties
  main-is: main.hs
  hs-source-dirs: apps/demo, test
  other-modules:
    Demo,
    DemoPrelude,
  ghc-options: -threaded -rtsopts -with-rtsopts=-N
  build-depends: alba, asciichart

executable test
  import: shared-properties
  main-is: test.hs
  hs-source-dirs:
      test
  other-modules:
      LibauthFileParse,
      LibauthSupport,
      QuickCheckSupport,
      TestArguments,
      TestBitwise,
      TestCheckMultiSig,
      TestCheckSig,
      TestCond,
      TestCodeMetrics,
      TestConstants,
      TestCustomTypes,
      TestDataPushing,
      TestDataSig,
      TestLookupTables,
      TestFunctions,
      TestFunctionsLowLevel,
      TestIntPushing,
      TestInteger,
      TestIntrospection,
      TestInvalidStack,
      TestLambdas,
      TestLibTuple,
      TestLibMaybe,
      TestLibVector,
      TestLibauthVectors2025,
      TestLibauthVectors2026,
      TestLibauthVectorsExclusions2025,
      TestLibauthVectorsExclusions2026,
      TestLoops,
      TestLzss,
      TestOpcodes,
      TestOpsArithmetic,
      TestOpsBytes,
      TestOpsConditional,
      TestOpsHash,
      TestOpsOrdering,
      TestOpsStack,
      TestOptimizer,
      TestStackBranches,
      TestRuntimeLib,
      TestTurtleVm2025,
      TestTurtleVm2026,
      TestUtils,
      TestUtils2026,
  build-depends: alba, scientific

executable benchmark1
  import: shared-properties
  hs-source-dirs: benchmark
  main-is: benchmark1.hs
  other-modules: BenchmarkOpcodeDispatch,
  ghc-options: -threaded -rtsopts -with-rtsopts=-N
  build-depends: alba, criterion, deepseq

executable benchmark2
  import: shared-properties
  hs-source-dirs: benchmark, test
  main-is: benchmark2.hs
  other-modules:
  ghc-options: -threaded -rtsopts -with-rtsopts=-N
  build-depends: alba, criterion, deepseq

executable ecmul
  import: shared-properties
  hs-source-dirs: apps/ecmul, test
  main-is: main.hs
  ghc-options: -threaded -rtsopts -with-rtsopts=-N
  build-depends: alba
